---
- name: Update the apt cache.
  apt:
    update_cache: yes

- name: Make sure that snapd is installed.
  apt:
    name:
      - snapd
    install_recommends: false
    state: present

- name: Install the core and the lxd snap.
  community.general.snap:
    name:
      - core
      - lxd

- name: Initialize lxd with default values.
  command: /snap/bin/lxd init --auto

- name: Add the user {{ edi_user }} to the group lxd.
  ansible.builtin.user:
    name: "{{ edi_user }}"
    groups: lxd
    append: yes

- name: Create an ssh key for the user {{ edi_user }}.
  ansible.builtin.user:
    name: "{{ edi_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

